### ISSUE TITLE
Crashing if page content is set to "Articles category"

### ISSUE THREAD

**Issue by snegovick** [misli/django-cms-articles#3]

**Comment by snegovick** [comment]
The root of the problem is in https://github.com/misli/django-cms-articles/blob/f7397bd5e303be6ed50bc53b71e27e40f4087f94/cms_articles/models/plugins.py#L123 . This line seems to be copied from https://github.com/misli/django-cms-articles/blob/f7397bd5e303be6ed50bc53b71e27e40f4087f94/cms_articles/models/plugins.py#L123 .

**Comment by misli** [comment]
Thank You, Konstantin, I've just released version, which includes Your patch.
